[tool.poetry]
name = "pages"
version = "0.1.0"
description = ""
authors = ["Willow Ahrens <willow@csail.mit.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
bibtexparser = "v2.0.0b7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
